# Generated by Django 4.1.7 on 2023-03-11 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='city_name')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='country_name')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('acronym', models.CharField(max_length=15)),
                ('logo_pic', models.ImageField(upload_to='logos')),
                ('overview', models.TextField()),
                ('date_established', models.DateField()),
                ('total_students', models.PositiveIntegerField()),
                ('international_students', models.PositiveIntegerField()),
                ('website', models.URLField()),
                ('acceptance_rate', models.FloatField()),
                ('uni_type', models.CharField(choices=[('public university', 'public university'), ('private university', 'private university'), ('liberal arts college', 'liberal arts college'), ('community college', 'community college')], max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.city')),
            ],
            options={
                'verbose_name_plural': 'universities',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.country'),
        ),
    ]
